services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
    network_mode: host
    hostname: plex
    restart: unless-stopped
    volumes:
      - /mnt/shm:/transcode
      - /mnt:/mnt
      - /opt/plex:/config
      - /opt/scripts:/scripts

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/Prowlarr-Indexers/config:/config
      - /opt/Prowlarr-Indexers/Custom:/config/Definitions/Custom
    ports:
      - 9696:9696
    restart: unless-stopped
      
  requestrr:
    image: thomst08/requestrr:latest
    container_name: requestrr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/requestrr:/config
    ports:
      - 4545:4545
    restart: unless-stopped
      
  radarr:
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    hostname: radarr
    image: ghcr.io/binhex/arch-radarr:latest
    restart: unless-stopped
    volumes:
      - /mnt:/mnt
      - /opt/radarr:/config
      - /opt/scripts:/scripts
      - /usr/bin/rclone:/usr/bin/rclone
      - /mnt/symlinks:/mnt/symlinks

  sonarr:
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8989:8989
    hostname: sonarr
    image: ghcr.io/binhex/arch-sonarr:latest
    restart: unless-stopped
    volumes:
      - /mnt:/mnt
      - /opt/scripts:/scripts
      - /opt/sonarr:/config
      - /usr/bin/rclone:/usr/bin/rclone
      - /mnt/symlinks:/mnt/symlinks
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
