services:
  plex:  # 📺 Plex Media Server - Streams your local media (movies, TV shows, music)
    container_name: plex
    image: plexinc/pms-docker:latest
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
    network_mode: host
    hostname: plex
    restart: unless-stopped
    volumes:
      - /mnt/shm:/transcode
      - /mnt:/mnt
      - /opt/plex:/config
      - /opt/scripts:/scripts

  prowlarr:  # 🧠 Prowlarr - Centralized indexer manager for Sonarr/Radarr
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/Prowlarr-Indexers/config:/config
      - /opt/Prowlarr-Indexers/Custom:/config/Definitions/Custom
    ports:
      - 9696:9696
    restart: unless-stopped

  requestrr:  # 💬 Requestrr - Discord bot for requesting movies and shows
    image: thomst08/requestrr:latest
    container_name: requestrr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/requestrr:/config
    ports:
      - 4545:4545
    restart: unless-stopped

  radarr:  # 🎬 Radarr - Automates movie downloads and management
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    hostname: radarr
    image: ghcr.io/binhex/arch-radarr:latest
    restart: unless-stopped
    volumes:
      - /mnt:/mnt
      - /opt/radarr:/co
